[Main]
# Level of log verbosity 0 - panic, 1 - fatal, 2 - error, 3 - warn, 4 -info, 5 - debug
LogLevel=4

[BlockChain]
# Amount of transactions that can be included to block
BlockSize=1
# Flush timeout in seconds when block sync to disk
Timeout=60
# Restrictions on transactions size
KeyMaxSize=5
ValueMaxSize=512
IndexOn=false
# Path to file that contains blockchain records
DataFile="../data/blockchain.dat"

[Http]
ListenStr="0.0.0.0:8080"
# Read/Write timeout in seconds
Timeout=10