[Main]
# Level of log verbosity 0 - panic, 1 - fatal, 2 - error, 3 - warn, 4 -info, 5 - debug
LogLevel=5

[BlockChain]
# Amount of transactions that can be included to block
BlockSize=1
# Flush timeout in seconds when block sync to disk
Timeout=60
# Restrictions on transactions size
KeyMaxSize=6
ValueMaxSize=512
IndexOn=true
# Path to file that contains blockchain records
DataFile="blockchain.dat"

[Index]
# Index types - BloomFilter, InvertedIndex
IndexType = "InvertedIndex"
IsOn = true

[Http]
ListenStr="0.0.0.0:8080"
# Read/Write timeout in seconds
Timeout=10